### ISSUE TITLE
explicitly use wxpython==4.0.3

### ISSUE THREAD

**Issue by cartertemm** [mush42/bookworm#1] opened 2019-07-15 10:17 UTC
In versions of wxpython>4.0.3, representation of control labels aren't necessarily what you'd want. The contrast can easily be seen by running:

```
pip install wxpython==4.0.3
invoke run
```

It might be helpful from a usability perspective to rely on this older version until something else is done by the folks at WxWidgets.
If anyone knows another way of keeping this more elegant interface in later versions, I'd love to hear about it.

**Comment by mush42** [comment] 2019-07-17 14:43
Hi @cartertemm

Yes you're right. There are severe accessibility regressions in wxPython from v4.0.4 onwards. I'm aware of this issue, and perhaps this is what preventing me from releasing any compiled binaries right now.

*Bookworm* uses some python-language features that have been introduced in python-3.7,  and the problem with wxpython 4.0.3 is that there are no pip installable compiled wheels for python-3.7. 

According to my test, wxpython v4.0.6 fixed most of the a11y issues, in 64-bit systems only.

A good news though, is that wxpython v4.1.0 is on its way, and it fixes the existing a11y issues. Additionally, it completes the implementation of wx.Accessible which allows us to expose more information about ui elements, for example we can change the role of the text control to be a document instead of text.

Alpha builds of wxpython v4.1.0 could be downloaded from [the wxpython snapshots page](https://wxpython.org/Phoenix/snapshot-builds/)

Please test with your environment.

Thanks

**Comment by mush42** [comment] 2019-07-17 15:02
Hi @cartertemm

Yes you're right. There are severe accessibility regressions in wxPython from v4.0.4 onwards. I'm aware of this issue, and perhaps this is what preventing me from releasing any compiled binaries right now.

According to my test, wxpython v4.0.6 fixed most of the a11y issues, at least in 64-bit systems.

A good news though, is that wxpython v4.1.0 is on its way, and it fixes the existing a11y issues. Additionally, it completes the implementation of wx.Accessible which allows us to expose more information about ui elements, for example we can change the role of the text control to be a document instead of text.

Alpha builds of wxpython v4.1.0 could be downloaded from [the wxpython snapshots page](https://wxpython.org/Phoenix/snapshot-builds/)

Please test with your environment.

Thanks

**Comment by mush42** [comment] 2019-07-17 15:06
In regard to moving to wxpython v4.0.3 ,we need some tests with that version because I've developed this application against wxpython 4.0.6. So some tests are required to insure nothing breaks.

**Closed** 2019-07-18 22:35 UTC
