### ISSUE TITLE
The "Rendered Page" dialog shows only a blank screen

### ISSUE THREAD

**Issue by k-kolev1985** [mush42/bookworm#9] opened 2019-09-09 07:58 UTC
## Describe the Problem

**NOTE:** I might be wrong, but I think that at least some vision may be required, in order to properly reproduce and diagnose this issue.

Even if a book is opened/loaded and even if it is being read aloud, when the "Render Page" function is executed, the dialog/screen that appears is a blank one. No content from the book (text and/or images) is displayed.

I use the high-contrast black theme in Windows 10 and at first I thought that the issue may be related to it (sometimes such issues occur in programs when a high-contrast theme is used in Windows). But I've disabled the usage of a high-contrast theme and the issue persisted.

## To Reproduce

1. Open Bookworm.
2. Open a book (the file format seams not to matter).
3. Optionally, press F5 to start reading the book aloud via SAPI5 TTS.
4. Execute the "Render page" function (pressing Control+R will do it).
5. Observe what is displayed on the screen.

## Expected behavior

A rendered version of the book's content should be displayed, but it is not - only a blank screen is shown.

## The File You've Opened

It does not matter if the file is EPUB or PDF. It does not matter if the text is in latin or cyrillic.

## Desktop (please complete the following information):

 - Operating system: Windows 10 Pro version 1903 (build 18362.329), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
 - Bookworm version: 0.1b2, x86 (32-bit).

**Comment by mush42** [comment] 2019-09-09 10:51
Hi kolev,

It seams that I can't reproduce this issue. I've tried with ePub and PDF, with text-to-speech enabled and disabled, and in all cases, the page is rendered properly.

What is the language of the eBook you've opened?

We've a long running issue of rendering ePub documents written in a non-Latin language. The problem has to do with setting appropriate font.

In other regard, can you try to navigate to another page, and navigate back to the page in question without leaving the render view? Does the page render properly after navigating back to it?

Regards,

**Comment by k-kolev1985** [comment] 2019-09-09 11:50
Oops, it seams that it is affected by the usage of the high-contrast theme, after all. To reproduce the issue, do the following, before opening Bookworm:
1. Go to Windows Settings (Windows+I) -> Ease of access -> High contrast -> Turn on high contrast and enable the high-contrast mode from that toggle switch.
2. From the combo box of available themes below the toggle, select "High Contrast Black".
3. Activate the "Apply" button on that screen.
4. Restart your computer.

When I disabled the usage of high-contrast mode and restarted my computer, the book content was rendered correctly. Even cyrillic text was displayed correctly, but that may be due to my language for non-Unicode programs been set correctly for my locale to "Bulgarian".

**Comment by mush42** [comment] 2019-09-09 12:55
Thanks very much.
I'll close this for now.

**Comment by k-kolev1985** [comment] 2019-09-09 18:02
May I ask what is the reason for closing it?

**Comment by mush42** [comment] 2019-09-09 20:06
My initial hunch is that we can not do anything about this issue.
WXPython, the widgets library we use with Bookworm, does not give us that granular control.
Anyway, I'll reopen it if we can find a work around.

Kind Regards,

**Comment by mush42** [comment] 2019-11-02 15:17
Also Fixed.

**Comment by mush42** [comment] 2019-11-04 12:26
Hi @k-kolev1985 

Please find a try build at https://github.com/mush42/bookworm/issues/3#issuecomment-549330513

**Closed** 2019-12-14 15:19 UTC
